apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: commonoptima-backend
  description: The backend service for the CommonOptima application.
  # Example for optional annotations
  annotations:
    github.com/project-slug: HZ-9000/CommonOptima-backend
  #   backstage.io/techdocs-ref: dir:.
spec:
  type: website
  owner: user:guest
  lifecycle: experimental
